var_1: &default_docker_image circleci/node:10.12
var_2: &browsers_docker_image circleci/node:10.12-browsers
var_3: &cache_key va-schematics-{{ checksum "package-lock.json" }}

# Settings common to each job
anchor_1: &defaults
  working_directory: ~/valueadd
  docker:
    - image: *browsers_docker_image

# After checkout, rebase on top of target branch.
anchor_2: &post_checkout
  run:
    name: Rebase PR on target branch
    command: >
      if [[ -n "${CIRCLE_PR_NUMBER}" ]]; then
        # User is required for rebase.
        git config user.name "va-ci"
        git config user.email "va-ci"
        # Rebase PR on top of target branch.
        node scripts/rebase-pr.js valueadd-poland/valueadd ${CIRCLE_PR_NUMBER}
      else
        echo "This build is not over a PR, nothing to do."
      fi

anchor_3: &restore_cache
  restore_cache:
    keys:
      - *cache_key
      # This fallback should be the cache_key without variables.
      - va-schematics-

anchor_4: &attach_options
  at: .

# Initializes the CI environment by setting up common environment variables.
anchor_5: &init_environment
  run:
    name: Initializing environment (setting up variables, overwriting Yarn)
    command: |
      # use git+ssh instead of https
      git config --global url."ssh://git@github.com".insteadOf "https://github.com" || true
      git config --global gc.auto 0 || true

anchor_6: &skip_github_host_check
  run:
    name: Avoid hosts unknown for github
    command: mkdir ~/.ssh/ && echo -e "Host github.com\n\tStrictHostKeyChecking no\n" > ~/.ssh/config

# Job definitions
version: 2
jobs:
  install:
    <<: *defaults
    steps:
      - checkout
      - *post_checkout
      - *restore_cache
      - *init_environment
      - run: npm install
      - persist_to_workspace:
          root: .
          paths:
            - ./*
      - save_cache:
          key: *cache_key
          paths:
            - ~/.cache/npm

  validate:
    <<: *defaults
    steps:
      - attach_workspace: *attach_options
      - *skip_github_host_check
      - run: npm run validate

  lint:
    <<: *defaults
    steps:
      - attach_workspace: *attach_options
      - run: './node_modules/.bin/prettier libs/**/*.{json,css,scss,js,ts,html} --list-different'
      - run: npm run affected:lint -- --base=origin/master --head=HEAD

  test:
    <<: *defaults
    steps:
      - attach_workspace: *attach_options
      - run: npm run affected:test -- --base=origin/master --head=HEAD

workflows:
  version: 2
  default_workflow:
    jobs:
      - install
      - validate:
          requires:
            - install
      - lint:
          requires:
            - install
      - test:
          requires:
            - install
